// auto generated file, do not edit
export type SupportedFrameworks =
  | 'html-webpack5'
  | 'svelte-vite'
  | 'preact-webpack5'
  | 'web-components-webpack5'
  | 'react-webpack5'
  | 'angular'
  | 'vue3-vite'
  | 'sveltekit'
  | 'web-components-vite'
  | 'react-vite'
  | 'svelte-webpack5'
  | 'ember'
  | 'nextjs'
  | 'preact-vite'
  | 'vue3-webpack5'
  | 'html-vite'
  | 'server-webpack5'
  | 'qwik'
  | 'solid';
