const path = require('path');

const addonsDir = (p) => `file:${path.join(__dirname, '../../addons', p)}`;
const appsDir = (p) => `file:${path.join(__dirname, '../../app', p)}`;
const libDir = (p) => `file:${path.join(__dirname, '../../lib', p)}`;

module.exports = process.env.LOCAL_STORYBOOK_PACKAGES_INSTALL
  ? {
      '@storybook/addon-a11y': addonsDir('a11y'),
      '@storybook/addon-actions': addonsDir('actions'),
      '@storybook/addon-backgrounds': addonsDir('backgrounds'),
      '@storybook/addon-controls': addonsDir('controls'),
      '@storybook/addon-cssresources': addonsDir('cssresources'),
      '@storybook/addon-design-assets': addonsDir('design-assets'),
      '@storybook/addon-docs': addonsDir('docs'),
      '@storybook/addon-essentials': addonsDir('essentials'),
      '@storybook/addon-events': addonsDir('events'),
      '@storybook/addon-google-analytics': addonsDir('google-analytics'),
      '@storybook/addon-graphql': addonsDir('graphql'),
      '@storybook/addon-jest': addonsDir('jest'),
      '@storybook/addon-knobs': addonsDir('knobs'),
      '@storybook/addon-links': addonsDir('links'),
      '@storybook/addon-queryparams': addonsDir('queryparams'),
      '@storybook/addon-storyshots': addonsDir('storyshots/storyshots-core'),
      '@storybook/addon-storyshots-puppeteer': addonsDir('storyshots/storyshots-puppeteer'),
      '@storybook/addon-storysource': addonsDir('storysource'),
      '@storybook/addon-toolbars': addonsDir('toolbars'),
      '@storybook/addon-viewport': addonsDir('viewport'),

      '@storybook/angular': appsDir('angular'),
      '@storybook/aurelia': appsDir('aurelia'),
      '@storybook/ember': appsDir('ember'),
      '@storybook/html': appsDir('html'),
      '@storybook/marionette': appsDir('marionette'),
      '@storybook/marko': appsDir('marko'),
      '@storybook/mithril': appsDir('mithril'),
      '@storybook/rax': appsDir('rax'),
      '@storybook/react': appsDir('react'),
      '@storybook/riot': appsDir('riot'),
      '@storybook/preact': appsDir('preact'),
      '@storybook/server': appsDir('server'),
      '@storybook/svelte': appsDir('svelte'),
      '@storybook/vue': appsDir('vue'),
      '@storybook/web-components': appsDir('web-components'),

      '@storybook/addons': libDir('addons'),
      '@storybook/api': libDir('api'),
      '@storybook/channel-postmessage': libDir('channel-postmessage'),
      '@storybook/channel-websocket': libDir('channel-websocket'),
      '@storybook/channels': libDir('channels'),
      '@storybook/cli': libDir('cli'),
      '@storybook/client-api': libDir('client-api'),
      '@storybook/client-logger': libDir('client-logger'),
      '@storybook/codemod': libDir('codemod'),
      '@storybook/components': libDir('components'),
      '@storybook/core': libDir('core'),
      '@storybook/core-events': libDir('core-events'),
      '@storybook/node-logger': libDir('node-logger'),
      '@storybook/postinstall': libDir('postinstall'),
      '@storybook/router': libDir('router'),
      '@storybook/source-loader': libDir('source-loader'),
      '@storybook/theming': libDir('theming'),
      '@storybook/ui': libDir('ui'),
    }
  : require('./versions.json');
