export const SLIDER_SAFE_PADDING = 3;
export const SLIDER_DEFAULT_OPACITY = 0.5;
export const SLIDER_DEFAULT_PADDING = 4;
export const SLIDER_DEFAULT_SIZE = 6;
export const SLIDER_DEFAULT_FADEOUT = 2000;
