/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RichData } from "./components/data/data-component";
export namespace Components {
    interface ContainerComponent {
    }
    interface DataComponent {
        "richData": RichData;
    }
}
declare global {
    interface HTMLContainerComponentElement extends Components.ContainerComponent, HTMLStencilElement {
    }
    var HTMLContainerComponentElement: {
        prototype: HTMLContainerComponentElement;
        new (): HTMLContainerComponentElement;
    };
    interface HTMLDataComponentElement extends Components.DataComponent, HTMLStencilElement {
    }
    var HTMLDataComponentElement: {
        prototype: HTMLDataComponentElement;
        new (): HTMLDataComponentElement;
    };
    interface HTMLElementTagNameMap {
        "container-component": HTMLContainerComponentElement;
        "data-component": HTMLDataComponentElement;
    }
}
declare namespace LocalJSX {
    interface ContainerComponent {
    }
    interface DataComponent {
        "richData"?: RichData;
    }
    interface IntrinsicElements {
        "container-component": ContainerComponent;
        "data-component": DataComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "container-component": LocalJSX.ContainerComponent & JSXBase.HTMLAttributes<HTMLContainerComponentElement>;
            "data-component": LocalJSX.DataComponent & JSXBase.HTMLAttributes<HTMLDataComponentElement>;
        }
    }
}
