// this file is generated by generate-exports-file.ts
// this is done to prevent runtime dependencies from making it's way into the build/start script of the manager
// the manager builder needs to know which dependencies are 'globalized' in the ui

export default {
  '@storybook/channels': {},
  '@storybook/core-events': {},
  '@storybook/core-events/preview-errors': {},
  '@storybook/preview-api': {},
  '@storybook/client-logger': {},
  '@storybook/types': {},
  '@storybook/instrumenter': {},
  '@storybook/core/dist/modules/channels/index': {},
  '@storybook/core/dist/modules/events/index': {},
  '@storybook/core/dist/modules/events/preview-errors': {},
  '@storybook/core/dist/modules/preview-api/index': {},
  '@storybook/core/dist/modules/client-logger/index': {},
  '@storybook/core/dist/modules/types/index': {},
  '@storybook/core/dist/modules/instrumenter/index': {},
  '@storybook/global': {},
} as const;
