name: Bug report ðŸž
description: >-
  Something is broken and you have a reliable reproduction? Let us know here.
  For questions, please post in GitHub Discussion.
title: '[Bug]: '
labels:
  - needs triage
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: input
    id: repro-link
    attributes:
      label: Reproduction link
      description: >-
        Please provide a link to a reproduction of the issue. We accept reproductions hosted on GitHub, CodeSandbox, and StackBlitz. Due to the high volume of reports, we prioritize those with clear reproductions. The easiest way to create a reproduction is to use [storybook.new](https://storybook.new). For detailed guidance, please refer to our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

        Important: If the provided URL is invalid (e.g., 404 error or private repository), we may close the issue. Thank you for your understanding!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: >-
        Include the steps to reproduce the issue using the provided link. Additionally, provide a clear and concise description of what you expected to happen.
      placeholder: >-
        1. Go to above link
        2. Click on '....'
        3. ...
  - type: textarea
    id: system
    attributes:
      label: System
      description: Please paste the results of `npx storybook@latest info` here.
      render: bash
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
