module.exports = {
  '/demo': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'index',
    title: 'Index',
    isFile: true,
    route: '/demo',
    files: ['/demo'],
    length: 1,
    contributors: {},
  },
  '/docs/api': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'api',
    title: 'Storybook API',
    isFile: true,
    route: '/docs/api',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/docs/cli': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'cli',
    title: 'Storybook CLI',
    isFile: true,
    route: '/docs/cli',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/docs/community': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'community',
    title: 'Community projects',
    isFile: true,
    route: '/docs/community',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/docs/configs': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'configs',
    title: 'Configuration',
    isFile: true,
    route: '/docs/configs',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/docs': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'index',
    title: 'Index',
    isFile: true,
    route: '/docs',
    files: [
      '/docs/api',
      '/docs/cli',
      '/docs/community',
      '/docs/configs',
      '/docs',
      '/docs/issues',
      '/docs/structure',
    ],
    length: 7,
    contributors: {},
  },
  '/docs/issues': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'issues',
    title: 'Issues',
    isFile: true,
    route: '/docs/issues',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/docs/structure': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'structure',
    title: 'Storybook structure',
    isFile: true,
    route: '/docs/structure',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/easteregg': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'easteregg',
    title: 'Hello world',
    isFile: true,
    route: '/easteregg',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/example': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'example',
    title: 'Core Addon API',
    isFile: true,
    route: '/example',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
      {
        hash: 'f9b12bc1aa320b434dff7ae42be6c561',
        name: 'Oleg Proskurin',
        meta: {},
      },
      {
        hash: '5f6b08ef71e8363145ea9de141945fff',
        name: 'Michael Shilman',
        meta: {},
      },
    ],
  },
  '/guides': {
    modified: '2017-09-23T20:09:37.000Z',
    name: 'index',
    title: 'Guides',
    isFile: true,
    route: '/guides',
    files: ['/guides', '/guides/setup', '/guides/why'],
    length: 3,
    contributors: {},
  },
  '/guides/setup': {
    modified: '2017-08-30T21:21:29.000Z',
    name: 'setup',
    title: 'Setup Storybook',
    isFile: true,
    route: '/guides/setup',
    files: [],
    contributors: [
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/guides/why': {
    modified: '2017-09-23T22:04:06.000Z',
    name: 'why',
    title: 'Why choose Storybook.',
    isFile: true,
    route: '/guides/why',
    files: [],
    contributors: [
      {
        hash: 'e8b22c40aa6826d9ee5473844191f3ec',
        name: 'Dan Green',
        meta: {
          github: 'dangreenisrael',
          npm: 'dangreenisrael',
        },
      },
      {
        hash: '537eed32d6998089dd5aa6a7e6ea2691',
        name: 'Norbert de Langen',
        meta: {
          github: 'ndelangen',
          npm: 'ndelangen',
          twitter: 'norbertdelangen',
        },
      },
    ],
  },
  '/': {
    modified: '2017-09-23T20:32:21.000Z',
    name: 'index',
    title: 'Index',
    isFile: true,
    route: '/',
    files: [],
    contributors: {},
  },
  '/contributing/maintainers-avoiding-burnout': {
    modified: '2017-09-24T17:26:23.000Z',
    name: 'maintainers-avoiding-burnout',
    title: 'Maintainers: Avoiding Burnout',
    isFile: true,
    route: '/contributing/maintainers-avoiding-burnout',
    files: [],
    contributors: {},
  },
  '/contributing/release-guide': {
    modified: '2017-09-24T17:29:14.000Z',
    name: 'release-guide',
    title: 'Release Guide',
    isFile: true,
    route: '/contributing/release-guide',
    files: [],
    contributors: {},
  },
  '/contributing/setting-up-a-dev-environment': {
    modified: '2017-09-24T17:26:23.000Z',
    name: 'setting-up-a-dev-environment',
    title: 'Setting up a dev environment (React)',
    isFile: true,
    route: '/contributing/setting-up-a-dev-environment',
    files: [],
    contributors: {},
  },
  '/contributing': {
    route: '/contributing',
    length: 7,
    files: [
      '/contributing/maintainers-avoiding-burnout',
      '/contributing/release-guide',
      '/contributing/setting-up-a-dev-environment',
      '/contributing',
      '/contributing/issue-triage',
      '/contributing/pull-requests',
      '/contributing/reporting-issues',
    ],
    modified: '2017-09-24T17:37:42.000Z',
    name: 'index',
    title: 'Index',
    isFile: true,
    contributors: {},
  },
  '/contributing/issue-triage': {
    modified: '2017-09-24T17:47:57.000Z',
    name: 'issue-triage',
    title: '',
    isFile: true,
    route: '/contributing/issue-triage',
    files: [],
    contributors: {},
  },
  '/contributing/pull-requests': {
    modified: '2017-09-24T17:46:24.000Z',
    name: 'pull-requests',
    title: 'Pull Requests (PRs)',
    isFile: true,
    route: '/contributing/pull-requests',
    files: [],
    contributors: {},
  },
  '/contributing/reporting-issues': {
    modified: '2017-09-24T17:44:21.000Z',
    name: 'reporting-issues',
    title: 'Reporting Issues',
    isFile: true,
    route: '/contributing/reporting-issues',
    files: [],
    contributors: {},
  },
};
