name: Unit tests

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Core Unit Tests, ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1

      - name: install and compile
        run: yarn task --task compile --start-from=auto --no-link
      - name: test
        run: yarn test
